abstract class AgentsDetails {
  static List<String> agentsNames = [
    "Viper",
    "Yoru",
    "Sova",
    "Skye",
    "Sage",
    "Reyna",
    "Raze",
    "Phoenix",
    "Omen",
    "Neon",
    "Killjoy",
    "Kayo",
    "Jett",
    "fade",
    "Cypher",
    "Chamber",
    "Brimstone",
    "Breach",
    "Astra",
    "Gekko",
    "Harbor",
  ];
  static Map<String, int> agentsNamesMap = {
    "Viper": 3,
    "Yoru": 2,
    "Sova": 4,
    "Skye": 4,
    "Sage": 1,
    "Reyna": 2,
    "Raze": 2,
    "Phoenix": 2,
    "Omen": 3,
    "Neon": 2,
    "Killjoy": 1,
    "Kayo": 4,
    "Jett": 2,
    "fade": 4,
    "Cypher": 1,
    "Chamber": 1,
    "Brimstone": 3,
    "Breach": 4,
    "Astra": 3,
    "Gekko": 3,
    "Harbor": 4,
  };
}
